### ISSUE TITLE
UDL sources for InterSystems contest

### ISSUE THREAD

**Issue by MakarovS96** [boanerges1227/AlertDashboard#1]
Please convert the sources from XML to UDL format to participate in the contest.
e.g. https://community.intersystems.com/post/vscode-load-xml-and-convert-udl#comment-117411
Or use ISC DEV to export in UDL: https://community.intersystems.com/post/isc-dev-continuous-export-classesrutinesdeepsee-files-working-directory
https://github.com/intersystems-community/isc-dev

**Comment by boanerges1227** [comment]
commit UDL sources
